package events

import (
	"context"
	"enman/internal/domain/battery"
	"time"
)

var BatteryScheduleSlots = genericEventHandler[BatteryScheduleSlotListener, *BatteryScheduleSlotEvent]{
	listeners: make(map[BatteryScheduleSlotListener]func(values *BatteryScheduleSlotEvent) bool),
}

func init() {
	// Initialize with a background context - will be set by application during startup
	BatteryScheduleSlots.SetContext(context.Background())
}

type BatteryScheduleSlotListener interface {
	HandleEvent(*BatteryScheduleSlotEvent)
}

// BatteryScheduleSlotEvent represents a new or updated battery schedule slot
// generated by the MILP optimizer
type BatteryScheduleSlotEvent struct {
	eventTime time.Time
	slot      *battery.ScheduleSlot
}

func NewBatteryScheduleSlotEvent(slot *battery.ScheduleSlot) *BatteryScheduleSlotEvent {
	return &BatteryScheduleSlotEvent{
		eventTime: time.Now(),
		slot:      slot,
	}
}

func (e *BatteryScheduleSlotEvent) EventTime() time.Time {
	return e.eventTime
}

func (e *BatteryScheduleSlotEvent) Slot() *battery.ScheduleSlot {
	return e.slot
}

func (e *BatteryScheduleSlotEvent) Valid() bool {
	return e.slot != nil
}
